---

- name: Add couchdb repo
  include_tasks: 'repo-{{ ansible_os_family }}.yml'
  tags: ['install']

- name: Install couchdb dependencies
  ansible.builtin.package:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present

- name: Install couchdb package
  ansible.builtin.package:
    name: couchdb
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Create couchdb group
  become: yes
  become_user: root
  ansible.buiting.group:
    name: couchdb
    state: present

- name: Create couchdb user
  become: yes
  become_user: root
  ansible.builtin.user:
    name: couchdb
    group: couchdb
    home: "/usr/local/couchdb"
    state: present


