---

- name: Add couchdb repo
  include_tasks: 'repo-{{ ansible_os_family }}.yml'
  tags: ['install']

- name: Install couchdb dependencies
  ansible.builtin.package:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present

- name: Install couchdb package
  ansible.builtin.package:
    name: couchdb
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Create couchdb group
  become: yes
  become_user: root
  ansible.builtin.group:
    name: couchdb
    state: present

- name: Create couchdb user
  become: yes
  become_user: root
  ansible.builtin.user:
    name: couchdb
    group: couchdb
    home: "/usr/local/couchdb"
    state: present

- name: Configure couchdb vm.args file
  become: yes
  become_user: root
  template:
    src: "{{ item }}"
    dest: /opt/couchdb/etc/{{ item | basename | regex_replace('\.j2', '') }}
    owner: couchdb
    group: couchdb
    mode: 0644
  with_fileglob:
    - templates/etc/vm.args.j2

- name: Configure couchdb from ini files
  become: yes
  become_user: root
  template:
    src: "{{ item }}"
    dest: /opt/couchdb/etc/local.d/{{ item | basename | regex_replace('\.j2', '') }}
    owner: couchdb
    group: couchdb
    mode: 0644
  with_fileglob:
    - templates/config/*.j2
  notify: Restart CouchDB service
