---

- name: Repo Debian | Add couchdb apt-key
  ansible.builtin.apt_key:
    url: https://couchdb.apache.org/repo/keys.asc
    state: present

- name: Repo Debian | Add couchdb apt-repo
  ansible.builtin.apt_repository:
    repo: "deb https://apache.jfrog.io/artifactory/couchdb-deb focal main"
