---
- name: verify

  hosts: all

  become: true

  tasks:

    - name: Verify CouchDB status
      uri:
        url: "http://localhost:5984"
        status_code: 200

    - name: Create test database
      uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 201

    - name: Verify test database exists
      uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 412

    - name: create CouchDB data backup
      ansible.builtin.command:
        cmd: /usr/local/bin/couchdb-backup

    - name: Delete test database
      uri:
        url: "http://localhost:5984/test_db"
        method: DELETE
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 200

    - name: Verify test database was deleted
      uri:
        url: "http://localhost:5984/test_db"
        method: DELETE
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 404

    - name: Restore CouchDB from data backup
      ansible.builtin.command:
        cmd: /usr/local/bin/couchdb-restore

    - name: Verify test database exists
      uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 412