---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'

    - name: Install gpg agent
      apt:
        name: gpg-agent
      when: (ansible_os_family | lower) == 'debian'

  roles:
    - role: wpnops.couchdb
