---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: coucdb_ubuntu_instance_2004
    image: geerlingguy/docker-ubuntu2004-ansible
    command: '/sbin/init'
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
verifier:
  name: testinfra
