---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter:  /usr/bin/python3
platforms:
  - name: localhost
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/converge.yml
