---
- name: converge

  hosts: all

  become: true

  roles:

    - pokerops.couchdb

  pre_tasks:

    - name: stop couchdb service
      ansible.builtin.service:
        name: "{{ couchdb_service_name }}"
        state: stopped

  post_tasks:

    - name: wait for service start
      ansible.builtin.wait_for:
        port: 5984

    - name: verify daemon status
      ansible.builtin.uri:
        url: "http://localhost:5984"
        status_code: 200
