---
- name: converge

  hosts: all

  become: true

  roles:

    - wpnops.couchdb

  pre_tasks:

    - name: stop couchdb service
      ansible.builtin.service:
        name: "{{ couchdb_service_name }}"
        state: stopped

  post_tasks:

    - name: verify daemon status
      uri:
        url: "http://localhost:5984"
        status_code: 200
