---
- name: verify

  hosts: all

  become: true

  tasks:

    - name: verify daemon status
      uri:
        url: "http://localhost:5984"
        status_code: 200

    - name: create test database
      uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 201

    - name: verify test database exists
      uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 412

    - name: delete test database
      uri:
        url: "http://localhost:5984/test_db"
        method: DELETE
        user: admin
        password: password
        force_basic_auth: yes
        status_code: 200
