---
- name: verify

  hosts: all

  become: true

  tasks:

    - name: verify authentication on main endpoint
      ansible.builtin.uri:
        url: "http://localhost:5984"
        status_code: 401

    - name: verify open status endpoint
      ansible.builtin.uri:
        url: "http://localhost:5984/_up"
        status_code: 200

    - name: create test database for user 1
      ansible.builtin.uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: "{{ couchdb_admins['admin'] }}"
        force_basic_auth: yes
        status_code: 201

    - name: verify test database exists for user 1
      ansible.builtin.uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: admin
        password: "{{ couchdb_admins['admin'] }}"
        force_basic_auth: yes
        status_code: 412

    - name: delete test database for user 1
      ansible.builtin.uri:
        url: "http://localhost:5984/test_db"
        method: DELETE
        user: admin
        password: "{{ couchdb_admins['admin'] }}"
        force_basic_auth: yes
        status_code: 200

    - name: create test database for user 2
      ansible.builtin.uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: test_admin
        password: password1
        force_basic_auth: yes
        status_code: 201

    - name: verify test database exists for user 2
      ansible.builtin.uri:
        url: "http://localhost:5984/test_db"
        method: PUT
        user: test_admin
        password: password1
        force_basic_auth: yes
        status_code: 412

    - name: delete test database for user 2
      ansible.builtin.uri:
        url: "http://localhost:5984/test_db"
        method: DELETE
        user: test_admin
        password: password1
        force_basic_auth: yes
        status_code: 200
