---
- name: converge

  hosts: all

  roles:
    - role: wpnops.couchdb

  vars:
    couchdb:
      require_auth: except_for_up
    couchdb_admins:
      admin: password
      test_admin: password1

  pre_tasks:

    - name: update apt cache.
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'

    - name: install gpg agent
      apt:
        name: gpg-agent
      when: (ansible_os_family | lower) == 'debian'
