---
name: molecule

on:

  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:
  run:
    working-directory: 'wpnops.couchdb'

jobs:

  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - geerlingguy/docker-ubuntu2004-ansible:latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'wpnops.couchdb'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install test dependencies.
        run: poetry install

      - name: Run Molecule tests.
        run: poetry run molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image }}
