---
name: molecule

on:

  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:
  run:
    working-directory: 'wpnops.couchdb'

jobs:

  focal:
    name: molecule-20.04
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scenario:
          - default
          - users
          - restore
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'wpnops.couchdb'

      - name: set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: run molecule tests.
        run: poetry run molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  impish:
    name: molecule-22.04
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        scenario:
          - default
          - users
          - restore
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'wpnops.couchdb'

      - name: set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: run molecule tests.
        run: poetry run molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
