---
name: molecule

on:

  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:
  run:
    working-directory: 'wpnops.couchdb'

jobs:

  molecule:
    name: molecule-20.04
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - distro: ubuntu2004
            command: /lib/systemd/systemd
          - distro: ubuntu2204
            command: /lib/systemd/systemd
        scenario:
          - default
          - users
          - restore
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'wpnops.couchdb'

      - name: set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: install podman
        run: apt-get install podman

      - name: configure podman registry
        run: poetry run ansible -m lineinfile localhost -a "path=/etc/containers/registries.conf line='unqualified-search-registries = [\"docker.io\"]'"

      - name: run molecule tests.
        run: poetry run molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_IMAGE_COMMAND: ${{ matrix.command }}
